export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQ_ROBOTS_PENDING = 'REQ_ROBOTS_PENDING';

export const REQ_ROBOTS_SUCCESS = 'REQ_ROBOTS_SUCCESS';

export const REQ_ROBOTS_FAILED = 'REQ_ROBOTS_FAILED';